pcall(require('telescope').load_extension, 'fzf')
local builtin = require('telescope.builtin')
vim.keymap.set('n', '<space>ff', builtin.fd, {})
vim.keymap.set('n', '<space>fg', builtin.live_grep, {})
vim.keymap.set('n', '<space>fb', builtin.buffers, {})
vim.keymap.set('n', '<space>fh', builtin.help_tags, {})
vim.keymap.set('n', '<space>fd', builtin.diagnostics, {})
vim.keymap.set('n', '<space>fk', builtin.keymaps, {})
require('telescope').load_extension('luasnip')
